
return {
  -- Colorschemes https://vimcolorschemes.com/
  -- https://dotfyle.com/neovim/colorscheme/trending
  { 'NLKNguyen/papercolor-theme' },
  { 'Verf/deepwhite.nvim' },
  { 'ajgrf/parchment' },
  { 'archseer/colibri.vim' },
  { 'axvr/raider.vim' },
  { 'catppuccin/nvim', name = 'catppuccin_theme' },
  { 'challenger-deep-theme/vim', name = 'challenger_deep_theme'},
  { 'cocopon/iceberg.vim' },
  { 'dracula/vim', name = 'dracula_theme' },
  { 'drazil100/dusklight.vim' },
  { 'echasnovski/mini.base16' },
  { 'embark-theme/vim', name = 'embark_theme' },
  { 'folke/tokyonight.nvim' },
  { 'jaredgorski/fogbell.vim' },
  { 'josebalius/vim-light-chromeclipse' },
  { 'kvrohit/mellow.nvim' },
  { 'lmburns/kimbox' },
  { 'mcchrish/zenbones.nvim' },
  { 'morhetz/gruvbox' },
  { 'nelstrom/vim-mac-classic-theme' },
  { 'nordtheme/vim', name = 'nord_theme'},
  { 'ntbbloodbath/sweetie.nvim' },
  { 'nyoom-engineering/oxocarbon.nvim' },
  { 'ok-ryoko/blue-screen' },
  { 'olivercederborg/poimandres.nvim' },
  { 'olivertaylor/vacme' },
  { 'oxfist/night-owl.nvim' },
  { 'oxfist/night-owl.nvim' },
  { 'preservim/vim-colors-pencil' },
  { 'progrimorio/nvim-nyctophilia' },
  { 'ray-x/aurora' },
  { 'rebelot/kanagawa.nvim' },
  { 'rose-pine/neovim', name = 'rosepine_theme' },
  { 'sainnhe/everforest' },
  { 'sainnhe/sonokai' },
  { 'savq/melange-nvim' },
  { 'slugbyte/lackluster.nvim' },
  { 'sts10/vim-pink-moon' },
  { 'wadackel/vim-dogrun' },
}
